#!/bin/sh

CC='cc'
STD='-std=c2x'
OPT='-Og'
DEBUG='-ggdb -fsanitize=address'
WARN='
    -Wimplicit
    -Werror
    -Wextra
    -Wall
    -Wpedantic
    -Wno-unused-function
    -Wno-stringop-overread
    -Wno-unused-value
'
